{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.efti.datatools",
    "module": "schema",
    "version": "0.10.0-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "schema-0.10.0-beta.1.jar",
          "url": "schema-0.10.0-beta.1.jar",
          "size": 62447,
          "sha512": "ef00e92a860d6a50991f5411640692dde6502f2110ea9f21936a2c880e7e4daf9c067900e1660e17a862c4a48ed47f0aa9053367a184a1dabb6d10f16678a571",
          "sha256": "18356ea8b9bfbc0cc51933dcf806dde1e0eb0cb6fe65030e1f68ac509de433c8",
          "sha1": "a7ae1194918c0eadb0d3cd2de18d474c4a3c30ea",
          "md5": "c0e228c5db9a4a816055513928c75427"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.xmlbeans",
          "module": "xmlbeans",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-bom",
          "version": {
            "requires": "2.25.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core"
        }
      ],
      "files": [
        {
          "name": "schema-0.10.0-beta.1.jar",
          "url": "schema-0.10.0-beta.1.jar",
          "size": 62447,
          "sha512": "ef00e92a860d6a50991f5411640692dde6502f2110ea9f21936a2c880e7e4daf9c067900e1660e17a862c4a48ed47f0aa9053367a184a1dabb6d10f16678a571",
          "sha256": "18356ea8b9bfbc0cc51933dcf806dde1e0eb0cb6fe65030e1f68ac509de433c8",
          "sha1": "a7ae1194918c0eadb0d3cd2de18d474c4a3c30ea",
          "md5": "c0e228c5db9a4a816055513928c75427"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.10.0-beta.1-javadoc.jar",
          "url": "schema-0.10.0-beta.1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.10.0-beta.1-sources.jar",
          "url": "schema-0.10.0-beta.1-sources.jar",
          "size": 17204,
          "sha512": "13684b1b0b658c9f8bc317a0fe61fa4998b11b0ead95db84a6fecd173d24cb18baf80f8e76a174c692869412cf0f618206e386039fdbef61bc2a130e9a955dca",
          "sha256": "cf552da8d6f5269c356ef2790132e11558d8439498f52e3ccb3ea9e3f7e3e2db",
          "sha1": "1eabd4a8a79e2e2e19a1bcfe479ba87419aac2da",
          "md5": "3d4e2034ad575ff0e55b42714be9d71f"
        }
      ]
    }
  ]
}
