version: 2
updates:
  # Keep Gradle dependencies up to date
  - package-ecosystem: "gradle"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # keep used GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
