{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.efti.datatools",
    "module": "schema",
    "version": "0.9.0-beta.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "schema-0.9.0-beta.2.jar",
          "url": "schema-0.9.0-beta.2.jar",
          "size": 43971,
          "sha512": "c128a025b5a00613acd639cde5b679d7efe0c3c8ca903e30cfba2d3f1006a02639101c591dad041dece700f129cf7d8d58e0792810f618029150a6728c841ea0",
          "sha256": "2b33e9f06c20b285a4a3eca684f8c4dee25bbaf8acc3f9083c51a305582762dc",
          "sha1": "44c4ed89bf12cc19435873011e07c21efcc76187",
          "md5": "fd356589788a7c491ac80cc2d1e51f26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.xmlbeans",
          "module": "xmlbeans",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-bom",
          "version": {
            "requires": "2.25.4"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core"
        }
      ],
      "files": [
        {
          "name": "schema-0.9.0-beta.2.jar",
          "url": "schema-0.9.0-beta.2.jar",
          "size": 43971,
          "sha512": "c128a025b5a00613acd639cde5b679d7efe0c3c8ca903e30cfba2d3f1006a02639101c591dad041dece700f129cf7d8d58e0792810f618029150a6728c841ea0",
          "sha256": "2b33e9f06c20b285a4a3eca684f8c4dee25bbaf8acc3f9083c51a305582762dc",
          "sha1": "44c4ed89bf12cc19435873011e07c21efcc76187",
          "md5": "fd356589788a7c491ac80cc2d1e51f26"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.9.0-beta.2-javadoc.jar",
          "url": "schema-0.9.0-beta.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.9.0-beta.2-sources.jar",
          "url": "schema-0.9.0-beta.2-sources.jar",
          "size": 10255,
          "sha512": "451418f67b6a7849f9c094588884d8b7ef457d70c09766e3e95a2fe4163ec9147cdbb2daf4aab30916dfd9f5e2af99e3771c7c2f14378f2b998fc3808b0cf6c1",
          "sha256": "5e18ef03b645557c719c8a6c6acb74ba18043a1bce8a6f5871eedc309485ebfb",
          "sha1": "518045d4b45f4f89e4c1abc67cbc843daf6a8605",
          "md5": "25d6dc0be8b88470fa025d3b18063849"
        }
      ]
    }
  ]
}
