{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.efti.datatools",
    "module": "schema",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "schema-0.7.0.jar",
          "url": "schema-0.7.0.jar",
          "size": 155480,
          "sha512": "f321b76bc99157859a662d1b7ad020b0e70864fa4540886e55f64d0adb0e39cec94829baea6ec46f7c03f9ee3f96d2154568d6d7c467c9bfe671e44ae82034f8",
          "sha256": "9aaae49715dd17a238cd051da9f7fdc89ddcf7502e540523dce67225891dbc16",
          "sha1": "4954c9774c3efe22842158ca6d19872692bed46c",
          "md5": "8a254e9caa95290659662872b67829d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.xmlbeans",
          "module": "xmlbeans",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-bom",
          "version": {
            "requires": "2.25.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core"
        }
      ],
      "files": [
        {
          "name": "schema-0.7.0.jar",
          "url": "schema-0.7.0.jar",
          "size": 155480,
          "sha512": "f321b76bc99157859a662d1b7ad020b0e70864fa4540886e55f64d0adb0e39cec94829baea6ec46f7c03f9ee3f96d2154568d6d7c467c9bfe671e44ae82034f8",
          "sha256": "9aaae49715dd17a238cd051da9f7fdc89ddcf7502e540523dce67225891dbc16",
          "sha1": "4954c9774c3efe22842158ca6d19872692bed46c",
          "md5": "8a254e9caa95290659662872b67829d3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.7.0-javadoc.jar",
          "url": "schema-0.7.0-javadoc.jar",
          "size": 261,
          "sha512": "aa1d7fd9aec455cef6e6c080457e563108ed6edf0e5193c65eb0f7f84cc2ced96567e9fc1b1606629e8c7215df4d255f2e24bfdf8c63087609889bc49cf2e392",
          "sha256": "10e8e17a9bc4495d06a6c19891d20d7d45278120e1e4284f994d5d083dd38b81",
          "sha1": "3f74a98e1207533b8990ff5e9dca5974772551ca",
          "md5": "2e51c8ba1e5a26f76ef03d04160edcd3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.7.0-sources.jar",
          "url": "schema-0.7.0-sources.jar",
          "size": 129213,
          "sha512": "69d46d35113af81c9ea27cb9cb314b7d49c0d6461740bc996e26f00323d88c8ba924e50ccc5298b6d51d3641bf64834dddb7a69fec5baf554df50f41a510d486",
          "sha256": "39be2109d5b0bae3850db99221caa77e011f2e7aca68dd44a2e4081fd4079c3d",
          "sha1": "aa9b23db719ce4665435836db8d66d48383637c2",
          "md5": "5158e638a11d9894309c226926d4c21b"
        }
      ]
    }
  ]
}
