{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.efti.datatools",
    "module": "populate",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "eu.efti.datatools",
          "module": "schema",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "populate-0.6.1.jar",
          "url": "populate-0.6.1.jar",
          "size": 39097,
          "sha512": "d131264bc8074cf588b3fd2f7d0070fcca227b8e986612be816a71cd7b37836e710ff118440c71401eeb6736f9dbcf2a1699f24f540ebe548e86a6fa1fa920ef",
          "sha256": "99ca94bd2b5dcf6d625e225c7767385c8b6f8f0e241245693e6546c50b9bc4c5",
          "sha1": "472335c6b15ae8b1d141dc9440a6c0b3722ff990",
          "md5": "6cef06d65de8089bd9d036b0577d39cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "eu.efti.datatools",
          "module": "schema",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "populate-0.6.1.jar",
          "url": "populate-0.6.1.jar",
          "size": 39097,
          "sha512": "d131264bc8074cf588b3fd2f7d0070fcca227b8e986612be816a71cd7b37836e710ff118440c71401eeb6736f9dbcf2a1699f24f540ebe548e86a6fa1fa920ef",
          "sha256": "99ca94bd2b5dcf6d625e225c7767385c8b6f8f0e241245693e6546c50b9bc4c5",
          "sha1": "472335c6b15ae8b1d141dc9440a6c0b3722ff990",
          "md5": "6cef06d65de8089bd9d036b0577d39cd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "populate-0.6.1-javadoc.jar",
          "url": "populate-0.6.1-javadoc.jar",
          "size": 261,
          "sha512": "b9b816ed61a29153498b1da46055f339dbca31d770e51116ebd557957f54436e2f5c2991b82b4c786e54abf1664f3cdfc6daec653ff41831fe95ec04daebf6f4",
          "sha256": "cad6aede7f340e4bfbc745dae609d30605b6057fe2b9352b1ef351e8d0377777",
          "sha1": "41ea1f52d4d2f6d0cb6a2717e5ae3c80cf1235a9",
          "md5": "d6ef24fa288ee08d6ad6dddbe17d8c9f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "populate-0.6.1-sources.jar",
          "url": "populate-0.6.1-sources.jar",
          "size": 5959,
          "sha512": "7cd1963c18e8c3083f6940889bdb4a4e5ca13b1c2da3c46ac16839ebc52a397783bc44b24f28dbe38cebb2a273d200525d1f9c44fd647e5dcc9d026db238f231",
          "sha256": "da4659c8e4b6e49bacc37c6f55a041c8c7d10e476c73e6714a70f9cae4589bd4",
          "sha1": "b7af5eb285cf0e92c352afc03ed5a9549032672c",
          "md5": "d07381114fbdf66326392dbe892172e0"
        }
      ]
    }
  ]
}
