{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.efti.datatools",
    "module": "populate",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "eu.efti.datatools",
          "module": "schema",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "populate-0.10.0.jar",
          "url": "populate-0.10.0.jar",
          "size": 52180,
          "sha512": "ff6895e366d473827d0acd30369ca277c691df264da73af8e66fc36120bd20375d20431495aa7906a7d652640a390b7a0f86ff6c3431cd89f59055e98c256c32",
          "sha256": "1bb5475083a331c3c54574eed733cf01e90398e0d033537cc71d2023ba0ee48b",
          "sha1": "7dcc6bf8d218f8a7e64e47ef72fb3cf41da7f76f",
          "md5": "1391dc931be5fd6063bb75426f7fc4b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "eu.efti.datatools",
          "module": "schema",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "populate-0.10.0.jar",
          "url": "populate-0.10.0.jar",
          "size": 52180,
          "sha512": "ff6895e366d473827d0acd30369ca277c691df264da73af8e66fc36120bd20375d20431495aa7906a7d652640a390b7a0f86ff6c3431cd89f59055e98c256c32",
          "sha256": "1bb5475083a331c3c54574eed733cf01e90398e0d033537cc71d2023ba0ee48b",
          "sha1": "7dcc6bf8d218f8a7e64e47ef72fb3cf41da7f76f",
          "md5": "1391dc931be5fd6063bb75426f7fc4b4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "populate-0.10.0-javadoc.jar",
          "url": "populate-0.10.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "populate-0.10.0-sources.jar",
          "url": "populate-0.10.0-sources.jar",
          "size": 10032,
          "sha512": "b4b66b72f84604a41103546ad2d570f3584b7b50cc611958e4f7c28d8490a55813a9592c12a68ba39840b434c901aa822399f3f53929a43a33f62c9d390359b0",
          "sha256": "7d01f0d60e38b4334e4394d7f8ca661f45300a8c69c92917e18554c5df68bb72",
          "sha1": "d495a7e4699da6814818ebb8b6debaa934309c17",
          "md5": "d2c8ed67331b76f079cb6b2be828f11d"
        }
      ]
    }
  ]
}
