{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.efti.datatools",
    "module": "populate",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "eu.efti.datatools",
          "module": "schema",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "populate-0.9.0.jar",
          "url": "populate-0.9.0.jar",
          "size": 39405,
          "sha512": "60d948e4b0546b7f2fc7783bf9985af38455ae0e236ac43371ce5fabc93d1239deee23a40fb460cef83bc033fa5bc93f523f32a32b429a9b3a618b1f882dd61d",
          "sha256": "1b9439895817488a0f37e9a41b52c7396f76a214ed5420fe92b63eee6006cea6",
          "sha1": "f92cc11b7e34d9717fb20abd1107d51ca8aad0bb",
          "md5": "5f69c68db0a03e7e5388b6e89df2d311"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "eu.efti.datatools",
          "module": "schema",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "populate-0.9.0.jar",
          "url": "populate-0.9.0.jar",
          "size": 39405,
          "sha512": "60d948e4b0546b7f2fc7783bf9985af38455ae0e236ac43371ce5fabc93d1239deee23a40fb460cef83bc033fa5bc93f523f32a32b429a9b3a618b1f882dd61d",
          "sha256": "1b9439895817488a0f37e9a41b52c7396f76a214ed5420fe92b63eee6006cea6",
          "sha1": "f92cc11b7e34d9717fb20abd1107d51ca8aad0bb",
          "md5": "5f69c68db0a03e7e5388b6e89df2d311"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "populate-0.9.0-javadoc.jar",
          "url": "populate-0.9.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "populate-0.9.0-sources.jar",
          "url": "populate-0.9.0-sources.jar",
          "size": 6146,
          "sha512": "e08984108baa998e617f0b19f894ef7963a7af56ae2e58b7e4a75c94aec474fa4e7b54b02fa92e7756d2fc70217284bb196d57cfa90001f10ee207e15e989fce",
          "sha256": "25b53635cb31fb24b37fc0686b4a57c448c84858973b8e6e710cc212e4830f9d",
          "sha1": "7254c3d7a616f309dd10fb9c5b611b135475a91c",
          "md5": "a43c4d364bd19596398c87932b13d98e"
        }
      ]
    }
  ]
}
