{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.efti.datatools",
    "module": "schema",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "schema-0.4.1.jar",
          "url": "schema-0.4.1.jar",
          "size": 154041,
          "sha512": "8f5b6736739324a63212ab2c85ca703b0ff29189e895c6877f344ba6935bf8a1e04d671808b0e2c81e380a0c346d3eadd52a926458661d45643c6b7eed728e02",
          "sha256": "9892a861fdad91d0e6a5cba7a0abb48e82a552fcd90dd7c2a0ff5a175385dbbb",
          "sha1": "cf3f09ffc91a84cca38cbb2eccb9f565fad3bce6",
          "md5": "51b5ab6995b3f0bdcb7f1186c339e8e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.xmlbeans",
          "module": "xmlbeans",
          "version": {
            "requires": "5.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-bom",
          "version": {
            "requires": "2.24.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core"
        }
      ],
      "files": [
        {
          "name": "schema-0.4.1.jar",
          "url": "schema-0.4.1.jar",
          "size": 154041,
          "sha512": "8f5b6736739324a63212ab2c85ca703b0ff29189e895c6877f344ba6935bf8a1e04d671808b0e2c81e380a0c346d3eadd52a926458661d45643c6b7eed728e02",
          "sha256": "9892a861fdad91d0e6a5cba7a0abb48e82a552fcd90dd7c2a0ff5a175385dbbb",
          "sha1": "cf3f09ffc91a84cca38cbb2eccb9f565fad3bce6",
          "md5": "51b5ab6995b3f0bdcb7f1186c339e8e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.4.1-javadoc.jar",
          "url": "schema-0.4.1-javadoc.jar",
          "size": 261,
          "sha512": "f5fdc4f25713755ff10bb9e8b4cb8325367e120a9aba31e519b282ed2d063188fbe112fe056a41b617d7f288a1569086a6d7189013b2f574ff26926d847021ed",
          "sha256": "357b28e59a7dc6c02de7c20c5cd288fb8128813092912fdf5c6135ac606e1c68",
          "sha1": "a24f8155b1ddab0bbcdf5710e48156150e8c5764",
          "md5": "81fa792dc0bbb34d8142751756c2cee2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.4.1-sources.jar",
          "url": "schema-0.4.1-sources.jar",
          "size": 128271,
          "sha512": "70da7910c9737857f28346bdd36d3b190ff99349c7a838fbee0126468edfe5d1e1c6c3f299bf2424d3670671cc6eb81ba0a02d98a105a60d0f0f92c70f485ea5",
          "sha256": "39941d0c6eb98f0990df095b05dab95775b723753dda4b712098920020d6d271",
          "sha1": "168cb90e46d97ce7566068ef0e7ed85515b9c57c",
          "md5": "7ffd00ce238ee206d8359526a0efc296"
        }
      ]
    }
  ]
}
