{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.efti.datatools",
    "module": "schema",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "schema-0.9.0.jar",
          "url": "schema-0.9.0.jar",
          "size": 44185,
          "sha512": "65f22ffeb4796ce777e69506ccef1eef5fbb1c9e454c4fc9cc6c0395efdb318e3cbb00c1b70771b6a658013213606d5fa74b9262a716b773a745a00da6b77f98",
          "sha256": "92f17d4532080952b5d92f2b0b93c0cf24cdb52b5552605cc416c53bc3ce7869",
          "sha1": "11add3a88a2a67f2ff55b194868cfebe883826b2",
          "md5": "77bd6604fb866305e08f1c18cd306f4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.xmlbeans",
          "module": "xmlbeans",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-bom",
          "version": {
            "requires": "2.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core"
        }
      ],
      "files": [
        {
          "name": "schema-0.9.0.jar",
          "url": "schema-0.9.0.jar",
          "size": 44185,
          "sha512": "65f22ffeb4796ce777e69506ccef1eef5fbb1c9e454c4fc9cc6c0395efdb318e3cbb00c1b70771b6a658013213606d5fa74b9262a716b773a745a00da6b77f98",
          "sha256": "92f17d4532080952b5d92f2b0b93c0cf24cdb52b5552605cc416c53bc3ce7869",
          "sha1": "11add3a88a2a67f2ff55b194868cfebe883826b2",
          "md5": "77bd6604fb866305e08f1c18cd306f4e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.9.0-javadoc.jar",
          "url": "schema-0.9.0-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "schema-0.9.0-sources.jar",
          "url": "schema-0.9.0-sources.jar",
          "size": 10255,
          "sha512": "451418f67b6a7849f9c094588884d8b7ef457d70c09766e3e95a2fe4163ec9147cdbb2daf4aab30916dfd9f5e2af99e3771c7c2f14378f2b998fc3808b0cf6c1",
          "sha256": "5e18ef03b645557c719c8a6c6acb74ba18043a1bce8a6f5871eedc309485ebfb",
          "sha1": "518045d4b45f4f89e4c1abc67cbc843daf6a8605",
          "md5": "25d6dc0be8b88470fa025d3b18063849"
        }
      ]
    }
  ]
}
